version: "3.2"

services:

  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/

  apache:
    build: './apache/'
    depends_on:
      - php
      - db
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: test

networks:
  frontend:
  backend:

volumes:
  mysql-data:
